keys:
  - &bresilla_yubikey age1yubikey1qgx8zafxpycdf2w4jug03ed5u2t5fdwshvhszmfxdhh27947c4sa6lf7hge
  - &system age1eyvczml8azx55esdg0rsjq48k760m0rq2aqjdht89dg0g9yy55nsd36wdw

creation_rules:
  - path_regex: secrets/system\.yaml$
    key_groups:
      - age:
          - *bresilla_yubikey
          - *system
  - path_regex: secrets/common/.*\.yaml$
    key_groups:
      - age:
          - *bresilla_yubikey
          - *system
  - path_regex: secrets/common/hosts$
    key_groups:
      - age:
          - *bresilla_yubikey
          - *system
