# Machine-specific layout generated by discio.sh; review devices before installing.
{
  disko.devices = {
    disk."disk1" = { type = "disk"; device = "/dev/nvme0n1";
      content = { type = "gpt"; partitions = {
        ESP = { priority = 1; size = "1024M"; type = "EF00";
          content = { type = "filesystem"; format = "vfat"; mountpoint = "/boot"; mountOptions = [ "umask=0077" ]; }; };
        pv = { size = "475908M"; content = { type = "lvm_pv"; vg = "pool"; }; };
      }; }; };
    lvm_vg."pool" = { type = "lvm_vg"; lvs = {
      "root" = { size = "32768M"; content = { type = "btrfs"; extraArgs = [ "-f" ]; subvolumes = { "/@root" = { mountpoint = "/"; mountOptions = [ "noatime" "compress=zstd:3" "ssd" ]; }; }; }; };
      "home" = { size = "32768M"; content = { type = "btrfs"; extraArgs = [ "-f" ]; subvolumes = { "/@home" = { mountpoint = "/home"; mountOptions = [ "noatime" "compress=zstd:3" "ssd" ]; }; }; }; };
      "nix" = { size = "163840M"; content = { type = "btrfs"; extraArgs = [ "-f" ]; subvolumes = { "/@nix" = { mountpoint = "/nix"; mountOptions = [ "noatime" "compress=zstd:3" "ssd" ]; }; }; }; };
      "doc" = { size = "131072M"; content = { type = "btrfs"; extraArgs = [ "-f" ]; subvolumes = { "/@doc" = { mountpoint = "/doc"; mountOptions = [ "noatime" "compress=zstd:3" "ssd" ]; }; "/@doc-code" = { mountpoint = "/doc/code"; mountOptions = [ "noatime" "compress=zstd:3" "ssd" ]; }; "/@doc-data" = { mountpoint = "/doc/data"; mountOptions = [ "noatime" "compress=zstd:3" "ssd" ]; }; "/@doc-self" = { mountpoint = "/doc/self"; mountOptions = [ "noatime" "compress=zstd:3" "ssd" ]; }; "/@doc-work" = { mountpoint = "/doc/work"; mountOptions = [ "noatime" "compress=zstd:3" "ssd" ]; }; }; }; };
      "pkg" = { size = "32768M"; content = { type = "btrfs"; extraArgs = [ "-f" ]; subvolumes = { "/@pkg" = { mountpoint = "/pkg"; mountOptions = [ "noatime" "compress=zstd:3" "ssd" ]; }; }; }; };
      "swap" = { size = "65536M"; content = { type = "swap"; }; };
    }; };
  };
}
